using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace _2
{
	class _2
	{
		/// <summary>
		/// http://projecteuler.net/problem=2
		/// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
		/// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
		/// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
		/// </summary>
		/// <param name="args"></param>
		static void Main(string[] args)
		{
			_2 main = new _2();
			Console.WriteLine("The sum of the even-values of a Fibonacci sequence, that does not exceed four million is " + main.fibonacci(4000000));
			Console.ReadKey();
		}

		private int fibonacci(int target)
		{
			int total = 0;
			int i = 1;
			int j = 2;
			int f;
			while (true)
			{
				f = i + j;
				i = j;
				j = f;
				if (j >= target)
					break;
				if (j % 2 == 0)
					total += j;
			}
			return total;
		}
	}
}
